import { init, setLocale, formatNumber, formatDate, notify } from '../js/timvw.js?v=0.7.0';
const locale = new URLSearchParams(location.search).get('lang') === 'nl' ? 'nl-BE' : 'en-GB';
const nl = locale.startsWith('nl');
setLocale(locale);
const messages = { skip: 'Naar inhoud', example: 'Taalvoorbeeld', title: 'Gemaakt voor jouw taal.', intro: 'Paginainhoud en componentmeldingen gebruiken dezelfde taal. Dit voorbeeld is beschikbaar in het Nederlands en Engels.', preferences: 'Voorkeuren', owner: 'Eigenaar', choose: 'Kies een eigenaar', password: 'Wachtwoord', showPassword: 'Wachtwoord tonen', save: 'Voorbeeld opslaan', formatting: 'Lokale notatie', budget: 'Budget', date: 'Datum', projects: 'Projecten', search: 'Zoeken', projectList: 'Voorbeeldprojecten', project: 'Project', back: 'Terug naar de uitgebreide voorbeelden' };
if (nl) document.querySelectorAll('[data-text]').forEach(node => { node.textContent = messages[node.dataset.text]; });
document.title = nl ? 'Nederlandstalige werkruimte · timvw' : 'English workspace · timvw';
document.getElementById('locale-number').textContent = formatNumber(12345.67, { style: 'currency', currency: 'EUR' });
document.getElementById('locale-date').textContent = formatDate(new Date('2026-09-11T12:00:00Z'), { dateStyle: 'long', timeZone: 'UTC' });
init(); document.getElementById('locale-save').hidden = false;
document.getElementById('locale-form').addEventListener('tvw:valid-submit', event => { event.preventDefault(); const message = nl ? 'Voorbeeld opgeslagen. Er is niets verzonden.' : 'Example saved. Nothing was sent.'; document.getElementById('locale-status').textContent = message; notify(message); });
