#!/usr/bin/env python3
"""Generate optional CSS families from the canonical, directly usable stylesheets."""
from pathlib import Path
import re
import json
import sys
ROOT = Path(__file__).resolve().parent.parent

def rules(text):
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.S).strip()
    pos = 0
    while pos < len(text):
        brace = text.find('{', pos)
        if brace < 0: break
        heading = text[pos:brace].strip()
        if ';' in heading: heading = heading.rsplit(';', 1)[1].strip()
        depth, end, quote = 1, brace + 1, None
        while depth:
            c = text[end]
            if quote:
                if c == quote and text[end - 1] != '\\': quote = None
            elif c in '\"\'': quote = c
            elif c == '{': depth += 1
            elif c == '}': depth -= 1
            end += 1
        yield heading, text[brace + 1:end - 1].strip()
        pos = end

families = {
    'theme': ('theme',), 'buttons': ('button','icon'), 'forms': ('field','input','help','error','choice','fieldset','switch','segmented','range'),
    'accordion': ('accordion',), 'cards': ('card',), 'feedback': ('badge','notice','empty','progress','skeleton'),
    'tables': ('table','sort','pagination'), 'navigation': ('nav','breadcrumbs'), 'tabs': ('tabs',),
    'dialogs': ('dialog','drawer'), 'overlays': ('popover','menu','tooltip','toast'),
    'layout': ('container','grid','page','app','statistic','definition'), 'select': ('combobox','option'),
    'chips': ('chip',), 'files': ('file',), 'workflows': ('step',), 'people': ('avatar',),
    'charts': ('chart',), 'details': ('detail','timeline'), 'commands': ('command',), 'foundation': ('stack','skip')
}
def split(text):
    result = {}
    def add(name, rule): result.setdefault(name, []).append(rule)
    for heading, body in rules(text):
        if heading in ('@layer timvw.tokens', '@layer timvw.base', '@layer timvw.utilities'):
            add('foundation', f'{heading} {{\n{body}\n}}')
        elif heading.startswith('@layer') or heading.startswith('@media'):
            for name, children in split(body).items(): add(name, f'{heading} {{\n'+'\n'.join(children)+'\n}')
        else:
            if heading.startswith('@keyframes'): name = 'buttons' if 'spin' in heading else 'feedback'
            else:
                match = re.search(r'\.tvw-([a-z]+)', heading)
                if not match: raise ValueError(f'Unclassified rule: {heading}')
                name = next((name for name, prefixes in families.items() if match[1] in prefixes), None)
                if not name: raise ValueError(f'Unclassified selector: {heading}')
            add(name, f'{heading} {{ {body} }}')
    return result

outputs = {}
for source in ('css/timvw.css', 'css/components.css'):
    for name, content in split((ROOT/source).read_text()).items(): outputs.setdefault(name, []).extend(content)
failed = []
for name, content in outputs.items():
    path = ROOT/'css'/('foundation.css' if name == 'foundation' else f'parts/{name}.css')
    preamble = '/* Generated by scripts/build-css.py from timvw.css and components.css. SPDX-License-Identifier: Apache-2.0.\n * QuantumBlack-derived color tokens: see THIRD_PARTY_NOTICES.md. */\n'
    if name == 'foundation': preamble += '@layer timvw.tokens, timvw.base, timvw.components, timvw.utilities;\n'
    text = preamble + '\n'.join(content) + '\n'
    if '--check' in sys.argv:
        if not path.exists() or path.read_text() != text: failed.append(str(path.relative_to(ROOT)))
    else: path.parent.mkdir(parents=True, exist_ok=True); path.write_text(text)
# Shadow components reuse canonical tokens without setting global CSS variables.
token_layer = next(body for heading, body in rules((ROOT/'css/timvw.css').read_text()) if heading == '@layer timvw.tokens')
palettes = {heading: dict(re.findall(r'(--tvw-[\w-]+)\s*:\s*([^;]+);', body)) for heading, body in rules(token_layer)}
light, dark = palettes[':root'], palettes[':root[data-tvw-theme="dark"]']
values = []
for key, value in light.items():
    fallback = f'light-dark({value}, {dark[key]})' if key in dark and key != '--tvw-shadow' else value
    if key == '--tvw-shadow': fallback = '0 16px 48px light-dark(oklch(20.64% 0.0205 271.56 / .12), rgb(0 0 0 / .3))'
    values.append(f'  {key.replace("--tvw-", "--_tvw-")}: var({key}, {fallback});')
shadow = '/* Generated from css/timvw.css by scripts/build-css.py. SPDX-License-Identifier: Apache-2.0.\n * QuantumBlack-derived tokens; see THIRD_PARTY_NOTICES.md. */\nexport default ' + json.dumps('.frame {\n' + '\n'.join(values) + '\n}\n') + ';\n'
path = ROOT/'components/tokens.js'
if '--check' in sys.argv:
    if not path.exists() or path.read_text() != shadow: failed.append(str(path.relative_to(ROOT)))
else: path.parent.mkdir(parents=True, exist_ok=True); path.write_text(shadow)
if failed: sys.exit('Outdated modular CSS: '+', '.join(failed))
print(f'{len(outputs)} modular stylesheets '+('verified.' if '--check' in sys.argv else 'generated.'))
